name: cd
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Setup Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud builds submit --tag europe-north2-docker.pkg.dev/notely-463609/notely-ar-repo/druwan/notely:latest"

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-north2-docker.pkg.dev/notely-463609/notely-ar-repo/druwan/notely:latest --region europe-north2 --allow-unauthenticated --project notely-463609 --max-instances=4
